### ISSUE TITLE
unstability on AGX Xavier running on MAXN power mode

### ISSUE THREAD

**Issue by ynjiun** [Pyrestone/jetson-fan-ctl#7]
I  installed this package on my AGX Xavier. It works! I love it.
But after a while, the system starts to automatically reboot sporadically.
I wonder why and investigate a little bit:
Setup: AGX Xavier is running at MAXN power mode, historically I would manually run "sudo jetson_clocks" to turn on the fan to 255 (maximal speed). But just once to change the fan speed.
Potential root cause of sporatical reset:
Now after install automagic-fan, every 2 secs, the fanctl.py will write fanspeed to /sys/devices/pwm-fan/target_pwm.
Hypothesis: while AGX is running at MAXN and it is known issue that in this mode AGX is very voltage/current sensitive. Every time when set_speed(spd) occurs, it might potentially create the voltage swing that might upset AGX to trigger the reset. 
Avoiding unnecessary set_speed(spd) strategy:
I modify the code to do following to reduce the frequency of set_speed(spd) while meets my need of thermal management yet still enjoy the silent when the unit is idle:
1. check if current spd is the same as prev_speed, then there is no need to call set_speed()
2. introduce optional (configurable) WATERMARK feature that only set the fan speed at two level (HI_FAN, LO_FAN) using watermark algorithms (HI_TEMP, LO_TEMP). This further reduce the frequency of touching set_speed()
3. make default UPDATE_INTERVAL longer from 2 sec to 17 sec.

I tested it with my AGX Xavier running MAXN power mode and the result is very stable now.

If you like to review my code and please provide me permission to push (branch: watermark) changes to you. Please let me know ; ))

Thank you again for your code. It helps a lot.

**Comment by Pyrestone** [comment]
That sounds more like a problem with your power supply being insufficient to provide the voltage (=torque) to accelerate the fan under load.
Jetsons are known to be sensitive to voltage drop.

The voltage drop from setting the fan speed for the driver should be minimal because that's a continuous pwm signal which just changes duty cycle when the fan speed is changed. The actual motor controller hardware for fan speeds sits on the fan itself.

So I assume it's one of two things:
1. Your power supply might not be able to sustain full load on jetson + Fan without voltage drop which the jetson sees and resets.
2. The fan driver on the agx might work differently than on the nano so accessing the fan speed "file" directly might upset the driver.

**Comment by Pyrestone** [comment]
Sidenote: this tool was written for Jetson Nano and I don't have an AGX so i can't guarantee anything with regards to other devices.
